/**
 * Dispatches classification to whichever provider is configured.
 *
 * All of this is main-process only, on purpose. The renderer has
 * `connect-src 'self'` and no route to either endpoint, so a key can never be
 * read out of a page — it lives here, is decrypted on demand, and is never sent
 * over IPC.
 *
 * Classification runs against the *thumbnail*, not the original: it is already
 * generated by an earlier stage, already capped at 512px, and already a format
 * both providers accept. Sending 4K originals would cost several times more per
 * image on the hosted provider and be markedly slower on a local one, while
 * telling the model nothing extra at this scale.
 */

import { readFile } from 'node:fs/promises'
import sharp from 'sharp'
import { AI_MODELS } from '@shared/types'
import type { AiSettings } from '@shared/types'
import * as anthropic from './providers/anthropic'
import * as openai from './providers/openai'
import type { ClassifyOutcome, ImageMediaType, ImagePayload } from './types'

export type { ClassifyOutcome } from './types'

/** Drops any memoised provider state, so changed settings take effect at once. */
export function resetClient(): void {
  anthropic.reset()
}

export async function classifyImage(
  thumbPath: string,
  settings: AiSettings,
  signal?: AbortSignal,
): Promise<ClassifyOutcome> {
  const image = await payloadFor(thumbPath, settings)

  return settings.provider === 'openai'
    ? openai.classify(image, settings, signal)
    : anthropic.classify(image, settings, signal)
}

/**
 * Reads the thumbnail in a format the target provider can actually decode.
 *
 * Thumbnails are WebP, which the Claude API accepts directly. Local servers
 * mostly cannot: LM Studio, Ollama, and everything else built on llama.cpp's
 * vision stack decode JPEG and PNG only, and hand back the thoroughly
 * misleading "'url' field must be a base64 encoded image" when given a WebP —
 * the base64 is fine, it just isn't an image *they* can read. So that path is
 * transcoded. It costs one small decode/encode per item and only happens for
 * the provider that needs it.
 */
async function payloadFor(thumbPath: string, settings: AiSettings): Promise<ImagePayload> {
  const raw = await readFile(thumbPath)

  if (settings.provider !== 'openai') {
    return { base64: raw.toString('base64'), mediaType: mediaTypeFor(thumbPath) }
  }

  const jpeg = await sharp(raw).jpeg({ quality: 85 }).toBuffer()
  return { base64: jpeg.toString('base64'), mediaType: 'image/jpeg' }
}

/** Confirms the configured provider is reachable and usable. Returns a summary. */
export async function testConnection(settings: AiSettings): Promise<string> {
  return settings.provider === 'openai' ? openai.test(settings) : anthropic.test(settings)
}

/**
 * Model ids to offer in the settings panel.
 *
 * Only an OpenAI-compatible server can actually be asked what it has loaded,
 * which is the whole reason this exists — with LM Studio the id has to match the
 * loaded model exactly, and guessing it from the UI is miserable. The Claude API
 * has no equivalent need, so it returns the built-in list.
 */
export async function listModels(settings: AiSettings): Promise<string[]> {
  if (settings.provider !== 'openai') return AI_MODELS.map((model) => model.id)
  return openai.listModels(settings)
}

function mediaTypeFor(path: string): ImageMediaType {
  if (path.endsWith('.png')) return 'image/png'
  if (path.endsWith('.gif')) return 'image/gif'
  if (path.endsWith('.jpg') || path.endsWith('.jpeg')) return 'image/jpeg'
  return 'image/webp'
}
